#!/usr/bin/perl
###
# plBake AUTHOR: Scott Sullivan (ssullivan@liquidweb.com)
# LWBake AUTHOR: Dennis Walters
#
# DESCRIPTION: Provides base tools to do installs.
#	       See plBake-functions. This is a perl take on
#	       LWBake originally by Dennis Walters.

use LWP::Simple;

if ( scalar(@ARGV) == 0 ) {
	print "You need to specify a recipe to install.\n";
	exit(1);
}
my $PLBAKEFUNCTIONS = 'http://scripts.ssullivan.org/plBake-functions';
our @args;
for my $arg (@ARGV) {
	push(@args, $arg);
};
our %params = map { $_ => 1 } @args;
our $recipe = $args[0];

sub source_http {
        my $url = $_[0];
        my $content = get ($url);
        if ( ! $content ) {
                die "plBake ERROR: Couldn't fetch recipe $url; is it a valid?\n";
        }
        eval $content; die $@ if $@;
}
source_http("$PLBAKEFUNCTIONS");

main();
